apiVersion: apps/v1
kind: Deployment
metadata:
  name: help-service-deployment
  labels:
    app: help-service
spec:
  replicas: 2  # Running with 2 replicas as required
  selector:
    matchLabels:
      app: help-service
  template:
    metadata:
      labels:
        app: help-service
    spec:
      containers:
      - name: help-service
        image: ismaill370/help-service:latest
        ports:
        - containerPort: 3002
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Liveness probe to check if the container is alive
        livenessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        # Readiness probe to check if the container is ready to receive traffic
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: help-service-config
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: help-service-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: help-service-secrets
              key: JWT_SECRET
---
# ConfigMap for non-sensitive environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: help-service-config
data:
  NODE_ENV: "development"
---
# Secret for sensitive environment variables
apiVersion: v1
kind: Secret
metadata:
  name: help-service-secrets
type: Opaque
data:
  # Base64 encoded secrets - replace with your actual encoded values
  # Note: These are using the values from docker-compose.yml, but they should be stored more securely
  MONGO_URI: bW9uZ29kYitzcnY6Ly9pc21haWx5YXNzZXIxMDY6ejF4MmMzMTJAYWl1LmJ3enZoY3IubW9uZ29kYi5uZXQvaGVscC1zZXJ2aWNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  JWT_SECRET: NzhkNzc0MTViNzU2YzMxMDU1NGIzYWMwMGNmNTBmNTJhYWVmNTY3NjMxOGViZTY3YjcyZDJhMzlkNGYzMjI3NA==
