apiVersion: v1
kind: Service
metadata:
  name: help-service
  labels:
    app: help-service
spec:
  type: ClusterIP  # Setting type as ClusterIP for internal access
  selector:
    app: help-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
