{{- if or .Values.secret.MONGO_URI .Values.secret.JWT_SECRET }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.MONGO_URI }}
  MONGO_URI: {{ .Values.secret.MONGO_URI | b64enc }}
  {{- end }}
  {{- if .Values.secret.JWT_SECRET }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | b64enc }}
  {{- end }}
{{- end }}
