apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    environment: production
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32000
