# Dockerfile for Gamification Service
FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm config set fetch-retries 5
RUN npm config set fetch-timeout 60000
RUN npm install
COPY . .
EXPOSE 3003
CMD ["npm", "start"]
