apiVersion: apps/v1
kind: Deployment
metadata:
  name: help-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: help-service
  template:
    metadata:
      labels:
        app: help-service
    spec:
      containers:
        - name: help-service
          image: ismaill370/help-service:latest
          ports:
            - containerPort: 3002
          envFrom:
          - configMapRef:
              name: help-service-config
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 3002
            initialDelaySeconds: 3
            periodSeconds: 5
