apiVersion: apps/v1
kind: Deployment
metadata:
  name: help-service-deployment
  labels:
    app: help-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: help-service
  template:
    metadata:
      labels:
        app: help-service
    spec:
      containers:
      - name: help-service
        image: ismaill370/help-service:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: help-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
