apiVersion: apps/v1
kind: Deployment
metadata:
  name: help-service-deployment
  labels:
    app: help-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: help-service
  template:
    metadata:
      labels:
        app: help-service
    spec:
      containers:
      - name: help-service
        image: help-service:local
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: help-service-config
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: help-service-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: help-service-secret
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
