apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9pc21haWx5YXNzZXIxMDY6ejF4MmMzMTJAYWl1LmJ3enZoY3IubW9uZ29kYi5uZXQvdXNlci1zZXJ2aWNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  JWT_SECRET: NzhkNzc0MTViNzU2YzMxMDU1NGIzYWMwMGNmNTBmNTJhYWVmNTY3NjMxOGViZTY3YjcyZDJhMzlkNGYzMjI3NA==
