apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  MONGO_URI: mongodb+srv://ismailyasser106:z1x2c312@aiu.bwzvhcr.mongodb.net/user-service?retryWrites=true&w=majority

  JWT_SECRET: 78d77415b756c310554b3ac00cf50f52aaef5676318ebe67b72d2a39d4f32274


