apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  # Basic service configuration
  PORT: '3000'
  NODE_ENV: 'production'

  # API configuration
  API_PREFIX: '/api/users'

  # CORS settings
  CORS_ORIGIN: '*'

  # Logging configuration
  LOG_LEVEL: 'info'

  # Health check configuration
  HEALTH_CHECK_INTERVAL: '30000'
  READINESS_CHECK_DELAY: '3000'

  # Rate limiting
  RATE_LIMIT_WINDOW_MS: '60000'
  RATE_LIMIT_MAX: '100'
  # Timeout settings
  REQUEST_TIMEOUT_MS: '5000'
  
  # MongoDB connection settings
  MONGODB_CONNECT_TIMEOUT_MS: '30000'
  MONGODB_SERVER_SELECTION_TIMEOUT_MS: '10000'
  MONGODB_SOCKET_TIMEOUT_MS: '30000'
  MONGODB_MAX_POOL_SIZE: '10'
  MONGODB_MIN_POOL_SIZE: '1'
