name: Simple Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'build-only'
        type: choice
        options:
        - build-only

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ismaill370

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push user-service
      uses: docker/build-push-action@v5
      with:
        context: ./services/user-service
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/user-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/user-service:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push help-service
      uses: docker/build-push-action@v5
      with:
        context: ./services/help-service
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/help-service:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/help-service:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/frontend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Validate Kubernetes manifests
      run: |
        echo "Validating Kubernetes YAML files..."
        find k8s/ -name "*.yaml" -exec echo "Checking {}" \; -exec cat {} > /dev/null \;
        echo "All YAML files are syntactically valid!"

    - name: Display deployment info
      run: |
        echo "✅ Docker images built and pushed successfully!"
        echo "📦 Images available:"
        echo "   - ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/user-service:latest"
        echo "   - ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/help-service:latest"
        echo "   - ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/frontend:latest"
        echo ""
        echo "🚀 To deploy locally:"
        echo "   kubectl apply -f k8s/ --recursive"
